apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-czhj
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci10t-786-0094-tenant/ci10t-786-0094-app/devfile-sample-czhj@sha256:7f0d302c47e7d9e6db915355426321116a763946aab818ea7d0162ec1c540ea3
        name: my-nodejs
        resources: {}
status: {}
