apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-czhj
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-czhj
    app.kubernetes.io/part-of: ci10t-786-0094-app
  name: devfile-sample-czhj
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-czhj
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-czhj
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci10t-786-0094-tenant/ci10t-786-0094-app/devfile-sample-czhj@sha256:7f0d302c47e7d9e6db915355426321116a763946aab818ea7d0162ec1c540ea3
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
